site_name: HouseHunt
site_url: https://jamils.github.io/HouseHunt
repo_url: https://github.com/jamils/HouseHunt
theme: 
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  favicon: assets/home.svg
  logo: assets/home.svg
  custom_dir: overrides
plugins:
  - search
markdown_extensions:
  - tables
extra_css:
  - assets/custom.css