site_name: House Hunt
site_description: A website to catalog houses
site_url: https://jamils.github.io/HouseHunt
repo_url: https://github.com/jamils/HouseHunt
theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/house
    admonition:
      info: fontawesome/solid/square-up-right
  custom_dir: overrides
  favicon: images/home.svg
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    #  - navigation.expand
    - navigation.top
    - navigation.instant.preview
    - navigation.instant.progress
plugins:
  - search
  - macros
  - open-in-new-tab
  - glightbox
markdown_extensions:
  - tables
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css

# nav:
#   - Home: index.md
#   - 1002 Shiloh St: 1002-shiloh-st.md
#   - 2607 Pioneer Rd: 2607-pioneer-rd.md
#   - 6308 Maywick Dr: 6308-maywick-dr.md
#   - 7800 Springbrook Dr: 7800-springbrook-dr.md
#   - 9009 Cannstatt Dr: 9009-cannstatt-dr.md
#   - 14009 Siniard Cir: 14009-siniard-cir.md
#   - 1112 Brookmeade St NW: 1112-brookmeade-st-nw.md
